config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tan-dolphin.sh
        container: qc.acc_homely-rust-seal
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-smalt-hyena.sh
        container: qc.doc_flimsy-gold-armadillo
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-seashell-bird.sh
        container: qc.doc_thirsty-magnolia-dogfish
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-peach-ostrich.sh
        container: qc.doc_boozy-alizarin-iguana
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-celadon-spider.sh
        container: qc.lic_foggy-mauve-booby
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-olivine-birman.sh
        container: qc.met_fuzzy-plum-hamster
timeout: 600
