config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-lavender-hornet.sh
        container: qc.acc_stinky-tangerine-gharial
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-magenta-mastiff.sh
        container: qc.doc_blurry-alizarin-squid
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-salmon-dachsbracke.sh
        container: qc.doc_chewy-cobalt-albatross
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cobalt-ocelot.sh
        container: qc.doc_snazzy-thistle-uguisu
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-olivine-rat.sh
        container: qc.lic_tasty-blue-squirrel
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lilac-capybara.sh
        container: qc.met_chewy-saffron-chinchilla
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-peach-uakari.sh
        container: qc.sec_thirsty-white-ant
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-grey-ragdoll.sh
        container: qc.sty_flabby-charcoal-magpie
timeout: 600
