config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-magnolia-pinscher.sh
        container: qc.acc_wiggy-cerise-devil
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-razzmatazz-burmese.sh
        container: qc.doc_scummy-tan-tzu
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-mustard-civet.sh
        container: qc.doc_sunny-cyan-yak
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ochre-shrimp.sh
        container: qc.doc_cozy-emerald-hyena
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-dandelion-retriever.sh
        container: qc.lic_scanty-asparagus-harrier
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-amber-affenpinscher.sh
        container: qc.met_snippy-indigo-paradise
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-lavender-loon.sh
        container: qc.sec_cloudy-olive-serval
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-asparagus-cat.sh
        container: qc.sty_sunny-mauve-goose
  QC.Ver:
    repos:
      github.com/lisc-tools/lisc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-indigo-civet.sh
        container: qc.ver_dorky-mauve-ibis
timeout: 600
