config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-mauve-donkey.sh
        container: qc.acc_greasy-cream-serval
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ultramarine-woodlouse.sh
        container: qc.doc_seedy-buff-chipmunk
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-chocolate-caracal.sh
        container: qc.doc_cheeky-cobalt-monster
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-orange-devil.sh
        container: qc.doc_freaky-blue-molly
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-lilac-okapi.sh
        container: qc.lic_cloudy-violet-baboon
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-zucchini-dunker.sh
        container: qc.met_hazy-russet-mouse
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-khaki-barnacle.sh
        container: qc.sec_sleazy-buff-termite
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-grey-salamander.sh
        container: qc.sty_scummy-purple-kangaroo
timeout: 600
