config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-bronze-kudu.sh
        container: qc.acc_tacky-brown-pinscher
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-buff-deer.sh
        container: qc.doc_lumpy-apricot-bloodhound
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-gold-dugong.sh
        container: qc.doc_snazzy-malachite-mandrill
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-vermilion-terrier.sh
        container: qc.doc_geeky-amaranth-owl
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-white-vulture.sh
        container: qc.lic_lovely-fuchsia-spider
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-blue-quoll.sh
        container: qc.met_pasty-orchid-beetle
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-heliotrope-wombat.sh
        container: qc.sec_gimpy-ultramarine-axolotl
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-black-audemer.sh
        container: qc.sty_muggy-lime-toucan
timeout: 600
