config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-chocolate-mandrill.sh
        container: qc.acc_scanty-aquamarine-leopard
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-mustard-earwig.sh
        container: qc.doc_snazzy-mauve-jellyfish
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-smalt-chinchilla.sh
        container: qc.doc_sickly-plum-quoll
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-firebrick-yak.sh
        container: qc.doc_crappy-aquamarine-frise
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-alizarin-crane.sh
        container: qc.lic_clammy-apricot-wasp
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.surly-periwinkle-squirrel.sh
        container: qc.met_silly-wisteria-mammoth
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cerise-monster.sh
        container: qc.sec_chewy-auburn-kiwi
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ivory-squirt.sh
        container: qc.sty_lumpy-sangria-blue
timeout: 600
