config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-white-zonkey.sh
        container: qc.acc_homey-blue-monster
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-beige-jaguar.sh
        container: qc.doc_shaky-magenta-koala
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-celadon-dogfish.sh
        container: qc.doc_muggy-celadon-mouse
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-dandelion-camel.sh
        container: qc.doc_shaggy-saffron-barb
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tangerine-frog.sh
        container: qc.lic_pretty-tangerine-mole
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-yellow-frise.sh
        container: qc.met_baggy-maroon-gibbon
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-firebrick-rabbit.sh
        container: qc.sec_flimsy-gamboge-tetra
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-harlequin-bobcat.sh
        container: qc.sty_woolly-wheat-octopus
  QC.Ver:
    repos:
      github.com/lisc-tools/lisc is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-seashell-zonkey.sh
        container: qc.ver_tacky-firebrick-hyena
timeout: 600
