config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-malachite-lionfish.sh
        container: qc.acc_crappy-ochre-toucan
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-apricot-bombay.sh
        container: qc.doc_boozy-cobalt-squirt
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-harlequin-insect.sh
        container: qc.doc_messy-puce-lion
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-olive-mammoth.sh
        container: qc.doc_jumpy-chestnut-wolverine
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-mauve-orangutan.sh
        container: qc.lic_seedy-cornflower-mongoose
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-maroon-affenpinscher.sh
        container: qc.met_bumpy-mustard-angora
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-mauve-chipmunk.sh
        container: qc.sec_goopy-orchid-audemer
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-chartreuse-earwig.sh
        container: qc.sty_nippy-lilac-kiwi
timeout: 600
