config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-khaki-zebu.sh
        container: qc.acc_queasy-silver-turkey
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-rust-stingray.sh
        container: qc.doc_muzzy-cardinal-russel
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-dandelion-rabbit.sh
        container: qc.doc_greasy-plum-mouse
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-coral-beagle.sh
        container: qc.doc_lumpy-lime-devil
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-lilac-ant.sh
        container: qc.lic_snappy-celadon-coyote
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-saffron-newfoundland.sh
        container: qc.met_gummy-harlequin-ray
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-mauve-chihuahua.sh
        container: qc.sec_skinny-pumpkin-cuttlefish
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-puce-gerbil.sh
        container: qc.sty_lumpy-salmon-saola
timeout: 600
