config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-fuchsia-wasp.sh
        container: qc.acc_zippy-zucchini-toucan
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-myrtle-tarantula.sh
        container: qc.doc_goopy-ochre-wolfhound
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-silver-rattlesnake.sh
        container: qc.doc_crabby-bronze-mouse
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lime-hornet.sh
        container: qc.doc_droopy-malachite-fousek
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ruby-barb.sh
        container: qc.lic_sickly-celadon-lemur
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-celadon-kiwi.sh
        container: qc.met_scanty-viridian-newt
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-ecru-beetle.sh
        container: qc.sec_cranky-seashell-tzu
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cerise-moose.sh
        container: qc.sty_beady-violet-spider
timeout: 600
