config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-black-cockroach.sh
        container: qc.acc_thirsty-celadon-rottweiler
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cerise-mayfly.sh
        container: qc.doc_slimy-cobalt-butterfly
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-white-bulldog.sh
        container: qc.doc_tasty-gold-tzu
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-beige-rat.sh
        container: qc.doc_boozy-pumpkin-quokka
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-myrtle-chameleon.sh
        container: qc.doc_surly-viridian-moose
  QC.FAIR:
    repos:
      github.com/lisc-tools/lisc F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.messy-heliotrope-sloth.sh
        container: qc.fair_wimpy-ochre-booby
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cardinal-octopus.sh
        container: qc.lic_zippy-heliotrope-dormouse
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-khaki-mayfly.sh
        container: qc.met_homey-ivory-penguin
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brass-molly.sh
        container: qc.sec_zippy-goldenrod-hyrax
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rose-albatross.sh
        container: qc.sty_squeaky-chestnut-chow
  QC.Ver:
    repos:
      github.com/lisc-tools/lisc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ivory-havanese.sh
        container: qc.ver_grumpy-magnolia-goat
timeout: 1800
