config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-viridian-toucan.sh
        container: qc.acc_trippy-lime-moorhen
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-amethyst-wallaby.sh
        container: qc.doc_squeaky-charcoal-panda
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-malachite-lobster.sh
        container: qc.doc_whiny-chocolate-coral
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-sangria-tang.sh
        container: qc.doc_gimpy-linen-oyster
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-chocolate-chameleon.sh
        container: qc.lic_jumpy-orchid-cockroach
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cobalt-meerkat.sh
        container: qc.met_cheeky-cream-clam
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amethyst-zebu.sh
        container: qc.sec_smelly-mustard-albatross
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-carmine-hound.sh
        container: qc.sty_nerdy-firebrick-robin
timeout: 600
