config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.4.0-alpha
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-khaki-bulldog.sh
        container: qc.acc_stinky-pear-catfish
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-teal-frigatebird.sh
        container: qc.doc_hazy-goldenrod-grasshopper
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cobalt-bison.sh
        container: qc.doc_scanty-cerulean-booby
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-pumpkin-bracke.sh
        container: qc.doc_slimy-maroon-spaniel
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-harlequin-bombay.sh
        container: qc.lic_snappy-pear-russel
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ruby-cassowary.sh
        container: qc.met_beady-ochre-donkey
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-malachite-gibbon.sh
        container: qc.sec_cranky-sapphire-jackal
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-sangria-havanese.sh
        container: qc.sty_homey-salmon-ferret
timeout: 600
