config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-zucchini-bongo.sh
        container: qc.acc_skimpy-cyan-tetra
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-lilac-vole.sh
        container: qc.doc_shabby-silver-mist
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-ochre-coral.sh
        container: qc.doc_wheezy-wisteria-barnacle
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-puce-dolphin.sh
        container: qc.doc_wimpy-sangria-moose
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-seal.sh
        container: qc.doc_baggy-asparagus-walrus
  QC.FAIR:
    repos:
      github.com/lisc-tools/lisc F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-thistle-blue.sh
        container: qc.fair_shaggy-fuchsia-balinese
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-aquamarine-neanderthal.sh
        container: qc.lic_woolly-sepia-javanese
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sapphire-boar.sh
        container: qc.met_shaky-buff-dhole
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-crimson-chimpanzee.sh
        container: qc.sec_skinny-olive-neanderthal
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-red-pig.sh
        container: qc.sty_baggy-amethyst-birman
  QC.Ver:
    repos:
      github.com/lisc-tools/lisc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-chocolate-chamois.sh
        container: qc.ver_cloudy-cornflower-dhole
timeout: 600
