config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-taupe-hippopotamus.sh
        container: qc.acc_lousy-bistre-monster
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pumpkin-lionfish.sh
        container: qc.doc_breezy-orchid-bee
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-amethyst-capybara.sh
        container: qc.doc_sloppy-olive-quetzal
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-harlequin-chinchilla.sh
        container: qc.doc_foggy-gold-mammoth
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-orchid-schnauzer.sh
        container: qc.lic_stinky-burgundy-iguana
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-carmine-ostrich.sh
        container: qc.met_homely-ultramarine-booby
timeout: 600
