config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lisc-tools/lisc:
      branch: main
      repo: https://github.com/lisc-tools/lisc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lisc-tools/lisc git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-mustard-owl.sh
        container: qc.acc_sleepy-tomato-chinook
  QC.Doc:
    repos:
      github.com/lisc-tools/lisc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-violet-gopher.sh
        container: qc.doc_frumpy-amber-gibbon
      github.com/lisc-tools/lisc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-goldenrod-dolphin.sh
        container: qc.doc_freaky-alizarin-eel
      github.com/lisc-tools/lisc restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-chestnut-earwig.sh
        container: qc.doc_jumpy-white-alligator
  QC.Lic:
    repos:
      github.com/lisc-tools/lisc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-dandelion-squirrel.sh
        container: qc.lic_snoopy-periwinkle-mastiff
  QC.Met:
    repos:
      github.com/lisc-tools/lisc cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-orange-capybara.sh
        container: qc.met_slaphappy-tan-goat
  QC.Sec:
    repos:
      github.com/lisc-tools/lisc bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cerise-eagle.sh
        container: qc.sec_chewy-cornflower-chihuahua
  QC.Sty:
    repos:
      github.com/lisc-tools/lisc flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-alizarin-eagle.sh
        container: qc.sty_grumpy-apricot-cat
  QC.Ver:
    repos:
      github.com/lisc-tools/lisc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cinnamon-beaver.sh
        container: qc.ver_surly-carmine-gharial
timeout: 600
